### ISSUE TITLE
`gyp_learnuv.py` fails for both python2 and python3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by Fulguritude** [thlorenz/learnuv#41]
```
$> python2.7 ./gyp_learnuv.py -f make                      
Traceback (most recent call last):
  File "./gyp_learnuv.py", line 93, in <module>
    (major, minor), is_clang = compiler_version()
ValueError: need more than 1 value to unpack
```

```
$> python3.8 ./gyp_learnuv.py -f make
  File "./gyp_learnuv.py", line 56
    print 'Error running GYP'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Error running GYP')?
```

**Comment by Fulguritude** [comment]
It seems the issue stemmed from my clang version returning a `version` tuple with `(10,)` so I hardcoded `(10,0)` for the version.
Additionally, my clang version is actually `11.0.0-2`, so why it returned 10, I have no idea.
